repo:
  url: https://github.com/codeleague/codecoach
  pr: 40
  token: 123qwe123qwe123qwe123
  userAgent: CodeCoach
  timeZone: Asia/Bangkok
buildLogFiles:
  - type: tslint
    path: /path/to/log.json
    cwd: /repo/src
output: ./output.json
